name: Deploy to Kubernetes

on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]

jobs:
  deploy:
    name: Deploy to Kubernetes
    runs-on: mehnaaz
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Create kubeconfig
      run: |
        echo ${{ secrets.KUBE_CONFIG }} | base64 --decode > ${HOME}/.kube/config
        cat ${HOME}/.kube/config
        id 
        sudo date
        sudo su root
        id
        pwd
        ls -lta         
    - name: Use context
      run: sudo kubectl config use-context minikube
    - name: Deploy to K8s
      run: |
        sudo su
        sudo kubectl apply -f k8s/
